SELECT 'default_banner_destination_url_trafficker' AS item, apa.value AS value FROM `ox_account_preference_assoc` AS apa 
WHERE apa.account_id = 224 AND apa.preference_id = 2 UNION SELECT 'default_banner_destination_url_manager' AS item, apa.value AS value 
FROM `ox_account_preference_assoc` AS apa 
WHERE apa.account_id = 222 AND apa.preference_id = 2 UNION SELECT 'default_banner_image_url_trafficker' AS item, apa.value AS value 
FROM `ox_account_preference_assoc` AS apa WHERE apa.account_id = 224 AND apa.preference_id = 1 UNION SELECT 'default_banner_image_url_manager' AS item, apa.value AS value 
FROM `ox_account_preference_assoc` AS apa WHERE apa.account_id = 222 AND apa.preference_id = 1 UNION SELECT 'default_banner_image_url_admin' AS item, apa.value AS value 
FROM `ox_account_preference_assoc` AS apa, `ox_accounts` AS a WHERE apa.account_id = a.account_id AND a.account_type = 'ADMIN' AND apa.preference_id = 1 UNION SELECT 'default_banner_destination_url_admin' AS item, apa.value AS value FROM `ox_account_preference_assoc` AS apa, `ox_accounts` AS a WHERE apa.account_id = a.account_id AND a.account_type = 'ADMIN' AND apa.preference_id = 2


SELECT d.bannerid AS ad_id, d.campaignid AS placement_id, d.status AS status, d.width AS width, d.ext_bannertype AS ext_bannertype, d.height AS height, d.storagetype AS type, d.contenttype AS contenttype, d.weight AS weight, d.adserver AS adserver, d.block AS block_ad, d.capping AS cap_ad, d.session_capping AS session_cap_ad, d.compiledlimitation AS compiledlimitation, d.acl_plugins AS acl_plugins, d.alt_filename AS alt_filename, az.priority AS priority, az.priority_factor AS priority_factor, az.to_be_delivered AS to_be_delivered, c.campaignid AS campaign_id, c.priority AS campaign_priority, c.weight AS campaign_weight, c.companion AS campaign_companion, c.block AS block_campaign, c.capping AS cap_campaign, c.session_capping AS session_cap_campaign, c.show_capped_no_cookie AS show_capped_no_cookie, c.clientid AS client_id, c.expire_time AS expire_time, c.revenue_type AS revenue_type, c.ecpm_enabled AS ecpm_enabled, c.ecpm AS ecpm, ct.status AS tracker_status, d.htmlcache REGEXP 'src\s?=\s?[\'"]http:' AS html_ssl_unsafe, d.imageurl REGEXP '^http:' AS url_ssl_unsafe FROM `ox_banners` AS d JOIN `ox_ad_zone_assoc` AS az ON (d.bannerid = az.ad_id) JOIN `ox_campaigns` AS c ON (c.campaignid = d.campaignid) LEFT JOIN `ox_campaigns_trackers` AS ct ON (ct.campaignid = c.campaignid) WHERE az.zone_id = 3 AND d.status <= 0 AND c.status <= 0 